# Generated by Django 5.0.2 on 2024-04-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
